# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: disabled

python:
  - "2.7"

os:
  - linux

git:
  depth: 1

env:
  global:
    - LOC=/home/travis/virtualenv/python2.7  # Location where VE is created on travis
    - CMD1="coverage run -m pytest -vvv tests/;flake8 tests/;pylint tests/"
    - CMD2="flake8 --config=.flake8 src/queue/queue.py"
    - CMD3="pylint src/queue/queue.py"
  matrix:
    - MAIN_CMD=$CMD1
    - MAIN_CMD=$CMD2
    - MAIN_CMD=$CMD3

# command to install dependencies
before_install:
  - pip install coverage
  - pip install flake8
  - pip install pylint
  - pip install codecov
  - pip install zmq
  - pip install msgpack

   
script:
  - echo $MAIN_CMD
  - eval $MAIN_CMD